### ISSUE TITLE
Error message when fire up npm start

### ISSUE THREAD

**Issue by cchoygithub** [gspncr/Node.js-Workshop#1]
New Relic for Node.js was unable to bootstrap itself due to an error:
Error: New Relic for Node.js requires a version of Node equal to or
greater than 10.0.0. Not starting!
    at initialize (/home/cchoy/Node.js-Workshop/node_modules/newrelic/index.js:57:13)
    at Object.<anonymous> (/home/cchoy/Node.js-Workshop/node_modules/newrelic/index.js:37:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/cchoy/Node.js-Workshop/app.js:1:78)
not sure

~~ Tried to update to the latest but still getting the same error message, thank you.

**Comment by gspncr** [comment]
hey @cchoygithub did you get this sorted? Looks like it started up as I left the "not sure" message in by accident 😜 which I will now fix. 
Leads me to think it is a version issue you faced?
